stages:
  - build
  - test

build_backend:
  image: mcr.microsoft.com/dotnet/sdk:7.0
  stage: build
  script:
    - echo "Starting build"
    - dotnet build
  artifacts:
    expire_in: 24 hours

backend_tests:
  image: mcr.microsoft.com/dotnet/sdk:7.0
  stage: test
  script:
    - echo "starting tests"
    - dotnet test
  dependencies:
    - build_backend

frontend_tests:
  image: node:16.15
  before_script:
    - cd mobile
    - npm install --legacy-peer-deps
    - cd ..
  stage: test
  script:
    - cd mobile
    - echo "Start JS tests for mobile"
    - npm run ci-test
    - cd ..
  allow_failure: false
  artifacts:
    when: always
    paths:
      - ./mobile/junit.xml
    reports:
      junit:
        - ./mobile/junit.xml