export type CountryDetails = {
  name: string;
  testID?: string;
};

export const countries: CountryDetails[] = [
  { name: "Albania", testID: "Albania" },
  { name: "Andorra" },
  { name: "Austria" },
  { name: "Åland Islands" },
  { name: "Belarus" },
  { name: "Belgium" },
  { name: "Bosnia and Herzegovina" },
  { name: "Bulgaria" },
  { name: "Croatia" },
  { name: "Cyprus" },
  { name: "Czech Republic" },
  { name: "Denmark" },
  { name: "Estonia" },
  { name: "Faroe Islands" },
  { name: "Finland" },
  { name: "France" },
  { name: "Germany" },
  { name: "Greece" },
  { name: "Guernsey" },
  { name: "Holy See (Vatican City State)" },
  { name: "Hungary" },
  { name: "Iceland" },
  { name: "Ireland" },
  { name: "Isle of Man" },
  { name: "Italy" },
  { name: "Jersey" },
  { name: "Latvia" },
  { name: "Liechtenstein" },
  { name: "Lithuania" },
  { name: "Luxembourg" },
  { name: "Macedonia, The Former Yugoslav Republic of" },
  { name: "Malta" },
  { name: "Moldova, Republic of" },
  { name: "Monaco" },
  { name: "Netherlands" },
  { name: "Norway" },
  { name: "Poland" },
  { name: "Portugal" },
  { name: "Romania" },
  { name: "Russian Federation" },
  { name: "San Marino" },
  { name: "Slovakia" },
  { name: "Slovenia" },
  { name: "Spain" },
  { name: "Svalbard and Jan Mayen" },
  { name: "Sweden" },
  { name: "Switzerland" },
  { name: "Ukraine" },
  { name: "United Kingdom" },
];
