
name: Build and submit apps through Expo EAS 

on:
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi      
      - name: Check for GOOGLE_SERVICES_JSON
        run: |
          if [ -z "${GOOGLE_SERVICES_JSON}" ]; then
            echo "You must provide a GOOGLE_SERVICES_JSON environment variable for this job. This should be a secret linked to this project's Google service account in this repo's secrets."
            exit 1
          fi
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: mobile/package-lock.json

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: |
          cd mobile
          npm install --legacy-peer-deps

      - name: Run script
        run: |
          cd mobile
          npm run create-stores-build
