
name: Build and submit apps through Expo EAS 

on:
  push:
    branches:
      - '**'

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi      

      - name: Check for GOOGLE_SERVICE_ACCOUNT_JSON
        run: |
          if [ -z "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" ]; then
            echo "You must provide a GOOGLE_SERVICE_ACCOUNT_JSON secret in this repo's secrets."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: mobile/package-lock.json

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: |
          cd mobile
          npm install --legacy-peer-deps

      - name: Write Google service account file and check if it has contents
        run: echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}' > ./mobile/google-service-account.json
              if [ ! -f "./mobile/google-service-account.json" ]; then
                echo "Failed to create the google-service-account.json file"
                exit 1
              elif [ ! -s "./mobile/google-service-account.json" ]; then
                echo "The google-service-account.json file is empty"
                exit 1
              fi

      - name: Run script
        run: |
          cd mobile
          npm run create-stores-build
