
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:7.0

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: dotnet build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: |
          **/bin
          **/obj

  backend_test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:7.0

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-output
        path: .

    - name: Backend tests
      run: dotnet test

  frontend_test:
    runs-on: ubuntu-latest
    container:
      image: node:16.15

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        cd mobile
        npm install --legacy-peer-deps

    - name: Frontend tests
      run: |
        cd mobile
        npm run ci-test

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: mobile/junit.xml
