
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:7.0

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: dotnet build

  backend_test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:7.0

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Backend tests
      run: dotnet test

  frontend_test:
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        cd mobile
        npm install --legacy-peer-deps

    - name: Frontend tests
      run: |
        cd mobile
        npm run ci-test

